name: Selenium Chrome CI Pipeline

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      # Checkout Project
      - name: Checkout Project
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4

        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v4

        with:
          path: ~/.m2

          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

          restore-keys: |
            ${{ runner.os }}-m2

      # Setup Chrome Browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # Run Selenium Tests
      - name: Run Selenium Tests
        run: mvn clean test -Dbrowser=chrome

      # Upload Extent Report
      - name: Upload Extent Report

        if: always()

        uses: actions/upload-artifact@v4

        with:
          name: ExtentReports
          path: test-output/
          if-no-files-found: ignore

      # Upload Screenshots
      - name: Upload Screenshots

        if: always()

        uses: actions/upload-artifact@v4

        with:
          name: FailureScreenshots
          path: screenshots/
          if-no-files-found: ignore

      # Upload Allure Results
      - name: Upload Allure Results

        if: always()

        uses: actions/upload-artifact@v4

        with:
          name: AllureResults
          path: allure-results/
          if-no-files-found: ignore

      # Slack Notification Success
      - name: Slack Success Notification

        if: success()

        run: |

          curl -X POST \
          -H 'Content-type: application/json' \
          --data "{
            \"text\": \":white_check_mark: Selenium Tests Passed\n\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nTriggered By: ${{ github.actor }}\nReport: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Slack Notification Failure
      - name: Slack Failure Notification

        if: failure()

        run: |

          curl -X POST \
          -H 'Content-type: application/json' \
          --data "{
            \"text\": \":x: Selenium Tests Failed\n\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nTriggered By: ${{ github.actor }}\nReport: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}